### ISSUE TITLE
Broadcast leak? Or I'm missing smthing

### ISSUE THREAD

**Issue by iRYO400** [vic797/prowebview#3]
```
BoardActivity has leaked IntentReceiver vcm.github.webkit.proview.ProWebView$1@25fbc97e that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                             android.app.IntentReceiverLeaked: Activity workshop.app.one.BoardActivity has leaked IntentReceiver vcm.github.webkit.proview.ProWebView$1@25fbc97e that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                 at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:909)
                                                                                 at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:710)
                                                                                 at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1663)
                                                                                 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1643)
                                                                                 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1637)
                                                                                 at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:489)
                                                                                 at vcm.github.webkit.proview.ProWebView.init(ProWebView.java:868)
                                                                                 at vcm.github.webkit.proview.ProWebView.<init>(ProWebView.java:332)
                                                                                 at vcm.github.webkit.proview.ProWebView.<init>(ProWebView.java:324)
```

**Comment by vic797** [comment]
ProWebView has a broadcast to check if there is connection. Looking at the code I noticed that the broadcast never gets unregistered. 

Also, thanks for the reports. I really appreciate it.

**Comment by vic797** [comment]
Well... I forgot something... Did you called `ProWebView.onDestroy();`

**Comment by iRYO400** [comment]
Nope, I dont call it 😄

**Comment by iRYO400** [comment]
I think, this one was the main reason. So I close it
